version: "2"

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    networks:
      - front-tier
      
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - front-tier

  nodeapp1:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    restart: always
    links:
      - redis
      - mongo
    ports:
      - "8080"
    volumes:
      - /Users/zxy/Desktop/CBRead_server/node-server:/src
      - /Users/zxy/Desktop/CBRead_server/node-server/.npmrc:/root/.npmrc
    networks:
      - front-tier

  nginx:
    build: ./nginx
    restart: always
    links:
      - nodeapp1
    ports:
      - "80:80"
    networks:
      - front-tier

networks:
  front-tier:
    driver: bridge