version: '2'

services:
  mongo-database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db

  node-server:
    image: zhang1024899756/cbread_server
    restart: always
    depends_on:
      - mongo-database
    links:
      - mongo-database
    ports:
      - 8000:8000

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - node-server
    links:
      - node-server