version: "2"

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379"
    networks:
      - front-tier
      
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017"
    networks:
      - front-tier

  nodebaise:
    build:
      context: ./baise-server
      dockerfile: Dockerfile
    restart: always
    links:
      - redis
      - mongo
    ports:
      - "8080"
    volumes:
      - /Users/zxy/Desktop/CBRead_server/baise-server:/src
      - /Users/zxy/Desktop/CBRead_server/baise-server/.npmrc:/root/.npmrc
    networks:
      - front-tier

  nodesocket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    restart: always
    links:
      - redis
      - mongo
    ports:
      - "8090"
    volumes:
      - /Users/zxy/Desktop/CBRead_server/socket-server:/src
      - /Users/zxy/Desktop/CBRead_server/socket-server/.npmrc:/root/.npmrc
    networks:
      - front-tier

  nginx:
    build: ./nginx
    restart: always
    links:
      - nodebaise
      - nodesocket
    ports:
      - "80:80"
    networks:
      - front-tier

networks:
  front-tier:
    driver: bridge