version: '3.7'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 8000:80
      - 80:80
    privileged: true
    volumes:
      - ./conf/proxy.conf:/etc/nginx/proxy.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/:/etc/nginx/conf.d/
      - ./html/:/usr/share/nginx/html/
      - ./logs/:/var/log/nginx/
    networks:
      - webapp-network
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network

  web:
    image: zhang1024899756/cbread_server
    restart: always
    depends_on:
      - database
    ports:
      - 8000:8000
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge