version: '1.0'

services:
  mongo-database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db

  node-server:
    image: zhang1024899756/cbread_server
    restart: always
    depends_on:
      - mongo-database
    links:
      - mongo-database
    expose:
      - 8000

  nginx:
    image: nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - node-server
    links:
      - node-server
    expose:
      - 8080