version: '3.7'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - webapp-network

  web:
    image: zhang1024899756/cbread_server
    restart: always
    depends_on:
      - database
    ports:
      - 8000:8000
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge